import Foundation

/// A role-specific script from one shared incident-review scenario. Built-in
/// scripts are templates: `{{name}}` is resolved once when a user creates a
/// named copy, so playback and caching never depend on mutable profile data.
struct ExampleExcerpt: Identifiable {
    static let namePlaceholder = "{{name}}"

    let id: String
    let role: String
    let audience: String
    let meeting: String
    let text: String

    var menuTitle: String { "\(role) — \(meeting)" }
    var wordCount: Int { text.split(whereSeparator: \.isWhitespace).count }

    static let all: [ExampleExcerpt] = [incidentManager, incidentTechnicalLead, incidentSupportLead]

    static let incidentManager = ExampleExcerpt(
        id: "incident-review-manager",
        role: "Engineering Manager",
        audience: "Technical Lead, Customer Support Lead, SRE, security, and product",
        meeting: "Authentication incident review",
        text: """
        I am {{name}}, the Engineering Manager facilitating today’s authentication incident review. Thank you for joining and for the work everyone did during the outage. Our purpose is to understand the conditions and decisions that allowed the incident, agree on changes that reduce both the chance and the impact of recurrence, and leave with named owners and verification dates. This is not a performance review of the individuals who responded. People acted with the information, tools, and incentives available at the time. If our conclusion is simply that someone should have noticed sooner or typed a different command, we will have missed the organizational and technical lessons. I’ll frame the impact and decisions, our Technical Lead will walk through the system behavior and remediation, and our Customer Support Lead will cover what customers experienced and how our communication performed.

        The incident began at 9:42 a.m. Pacific last Thursday and customer impact ended at 11:18 a.m., a total of ninety-six minutes. During that period, approximately thirty-eight percent of interactive login attempts failed. Existing sessions remained valid, and API traffic using long-lived service credentials was mostly unaffected. The highest impact was on customers whose identity providers require signed authentication requests. Twenty-three enterprise accounts opened support cases, and three customers activated their own severity-one process. We have found no evidence of unauthorized access, data exposure, or lost writes. This was an availability incident, not a confidentiality or integrity incident, but the severity of the login failure and the loss of customer trust justify our highest operational classification.

        Before we debate solutions, I want to confirm the shared timeline. At 9:15 the identity team began a planned certificate rotation. At 9:37 the authentication fleet started refreshing its signing configuration. At 9:42 metadata advertising the new public certificate became visible to customers while part of the fleet still used the old private key. Our first alert fired four minutes later. The on-call engineer acknowledged it at 9:48, support connected the first enterprise reports at 9:54, and an incident commander joined at 10:01. The certificate mismatch was identified at 10:17. The first rollback attempt did not resolve the issue because external identity providers had cached the new metadata. The team then converged the fleet on the new key through controlled restarts, with recovery beginning at 10:52 and the final stale instance leaving service at 11:07.

        I want to explicitly recognize what went well. Detection and acknowledgment were inside our objectives. Support correlated separate customer reports quickly instead of treating them as unrelated account problems. Security joined early, helped rule out forged requests, and preserved the evidence needed for this review. Once the mismatch was understood, the response team resisted restarting the entire fleet at once and used batches to protect existing sessions. The incident commander maintained a decision log and communications continued on a regular cadence even when diagnosis was incomplete. Those behaviors limited the blast radius and gave us a reliable record. We should preserve them while fixing the structural weaknesses that made diagnosis and recovery slower than necessary.

        The central lesson is that our rotation process encoded a timing assumption where it needed a compatibility protocol and an observable state transition. The runbook assumed secret refresh would complete within five minutes because it usually had before. It did not define a measurable completion condition, and no single owner was accountable for the full transition across the signer configuration and public metadata. The deployment check proved that new instances could sign with the new key; it did not prove that every serving instance had stopped using the old one. The rollback model was inherited from application deployments, where returning to an earlier version normally restores compatibility. That mental model does not hold when external systems cache public metadata.

        There are three high-priority action groups. First, we will redesign rotation around an overlap window. The new public certificate will be published alongside the current certificate before any signer uses the new private key. Representative external providers must fetch that dual-certificate metadata before the fleet changes. After telemetry proves every active signer uses the new fingerprint, the old certificate will remain available through a defined cache-expiration period. Only then can automation remove it. Our Technical Lead owns the design and implementation, with a target before the next production rotation in six weeks.

        Second, we will add evidence and guardrails to the deployment path. The pipeline must expose desired and observed key versions for every active instance. It must block retirement of a certificate while any signatures still use that fingerprint. Synthetic authentication will run against several external identity providers with different cache behavior, not only our internal provider. Dashboards and alerts will group failures by provider, region, application version, and signing fingerprint. Completion means an on-call engineer can identify a mixed fleet within five minutes during a staging exercise; it does not merely mean that a dashboard or alert definition has been merged.

        Third, we will improve the operating model around the change. The signer deployment and metadata publication steps will become one versioned workflow with an end-to-end owner, reviewer, verification window, and cache-aware recovery plan. The escalation alias will be generated from the current on-call schedule instead of being maintained by hand. Before the next rotation, we will run a game day that deliberately leaves part of the fleet stale, simulates a provider with a long metadata cache, and practices recovery. Engineering, SRE, security, support, and communications will all participate, because the incident exposed coordination gaps as well as a software flaw.

        We should also look beyond certificates. This failure belongs to a broader class of distributed transitions where producers and consumers cannot update atomically. Feature flags, encryption keys, webhook secrets, schema versions, and network policy changes may contain similar undocumented propagation assumptions. Architecture will lead a two-week review focused on transitions that can enter an incompatible intermediate state and cause broad customer impact. The goal is not a giant speculative backlog. We will prioritize cases where overlap, version negotiation, or observable convergence can materially reduce risk, and each accepted item will have a concrete test showing the transition is safe under delay.

        On customer follow-up, our Customer Support Lead will coordinate with account teams for the affected enterprises. The three customers who declared severity one need a direct summary of impact, confirmation that we found no security breach, the corrective-action plan, and a clear path for service-credit or security-documentation questions. Product and support will review whether any administrators need help validating their identity-provider configuration. We will publish the internal review after factual corrections today, then prepare an external version that is candid about the failure mode without exposing sensitive operational details. The external document must distinguish completed mitigation from planned prevention.

        For accountability, every action will have one owner, a date, and a verification artifact. “Improve monitoring” is not complete when a chart exists; it is complete when the game day triggers the alert, the responder reaches the fingerprint breakdown directly, and the mixed fleet is identified within the target time. “Update the runbook” is not complete when prose is merged; it is complete when a team unfamiliar with the implementation can follow it without ambiguous decisions. We will track these actions in the incident record, review high-priority work in two weeks, and keep the incident open until the overlap workflow and staging exercise pass.

        My final assessment is that this outage was preventable, but not because one person ignored an obvious instruction. Our system validated the destination and not the journey. It depended on an unmeasured refresh delay, exposed only one verification certificate, and used a rollback strategy that ignored external caches. The response team mitigated responsibly once the failure mode became visible. I am asking this group to approve the three action groups, their owners, and the six-week deadline. After the Technical Lead and Customer Support Lead add their evidence and corrections, I will publish the review and decision log today. We will reconvene for a short progress review in two weeks and a game-day readout before the next rotation.
        """
    )

    static let incidentTechnicalLead = ExampleExcerpt(
        id: "incident-review-technical-lead",
        role: "Technical Lead",
        audience: "Engineering Manager, Customer Support Lead, SRE, security, and product",
        meeting: "Authentication incident review",
        text: """
        I am {{name}}, the Technical Lead for the authentication platform. I’ll walk through the technical sequence behind last Thursday’s login incident, explain why our existing checks allowed the unsafe state, and propose the engineering changes that make the next certificate rotation compatible by construction. I agree with the Engineering Manager’s framing: the responders did not cause this outage by making an isolated bad choice. The system allowed two dependent operations to proceed as though they were independent, and it gave us no reliable way to observe when the fleet had converged. I’ll separate direct cause, contributing conditions, mitigation behavior, and corrective work so we do not blur what actually happened with what merely made diagnosis slower.

        Our outbound single sign-on requests are signed by an authentication fleet using a private certificate stored in the secrets service. Customers’ identity providers validate those signatures using public certificates fetched from our metadata endpoint. The rotation process had two distinct changes. One updated the private key reference and asked application instances to refresh. The other replaced the public certificate in metadata. Both operations were individually valid, but the protocol only remains compatible if verifiers can accept every key that a signer might use. At 9:37, instances began refreshing asynchronously. Some loaded the new key immediately, while long-lived instances retained the old key. At 9:42, metadata switched globally to only the new public certificate. From that moment, requests signed by stale instances could no longer be validated by providers that had fetched the new metadata.

        Our canary did not catch the problem because it answered a narrower question than we thought. It proved that a newly started instance could read the new secret and complete authentication through our internal identity provider. It did not sample signatures across the serving fleet, and it did not compare observed fingerprints with the certificates advertised publicly. The internal provider refreshes metadata quickly and the canary happened to reach updated instances, so every synthetic request passed while customers received a mixture of old and new signatures. The secrets controller emitted a successful refresh request event, but it did not report desired and observed versions per instance. We interpreted acceptance of work as completion of convergence.

        Detection started with a general rise in external identity-provider errors at 9:46. The aggregate dashboard grouped signature-validation failures with several other provider responses and did not expose the signing fingerprint. Because failures varied by customer and our internal provider remained healthy, the initial hypothesis was a regional or provider-specific issue. At 10:17 an engineer compared a failed signed request with the current metadata and saw that the request used the retired fingerprint. That comparison was manual. The relevant information existed in separate logs, but there was no correlated view and no alert annotation connecting the error increase to the certificate change. This increased time to diagnosis even though the initial alert itself fired promptly.

        The first mitigation was to restore the previous public certificate in metadata. That was reasonable under our application-deployment rollback model, but it was incomplete for this protocol. Several providers had already cached the new certificate and would not fetch metadata again for up to an hour. Reverting metadata therefore inverted the mismatch for some customers: updated signers now used a key that cached old metadata could not validate, while stale signers worked again for providers that refreshed. At 10:31 we changed strategy and decided to converge all signers on the new private key while publishing the new public certificate. We lacked a safe fleet-wide refresh command, so we restarted instances in controlled batches and watched login success, capacity, and fingerprint telemetry.

        Recovery began when more than ninety-five percent of signatures used the new fingerprint at 10:52. The last stale instance left service at 11:07, and error rates returned to baseline across customer segments by 11:18. Batched replacement was slower than a fleet restart, but it protected existing sessions and kept sufficient capacity available. The responders made the right tradeoff with the tools we had. The engineering failure was that our normal rotation path could create the inconsistent state while our emergency tools could not directly measure or repair it. A safe process should not depend on responders reconstructing distributed state from logs during an outage.

        The primary fix is a dual-certificate overlap protocol. At least twenty-four hours before a new private key becomes active, metadata will advertise both the current and next public certificates. Synthetic checks will verify that representative providers have fetched the dual set. The signer fleet can then roll gradually to the new private key because providers will accept signatures from either state. Every signer will report its active fingerprint as a metric and health attribute. Once one hundred percent of active instances use the new key and no signatures from the retiring key have appeared for a full external cache window, automation may remove the old public certificate. Each transition remains compatible even if propagation is slow.

        We will implement the rotation as a state machine rather than a sequence of loosely coupled runbook steps. Proposed states are prepared, dual-published, provider-verified, signer-rolling, converged, retirement-waiting, and complete. Moving between states requires machine-verifiable evidence, and unsafe transitions will be rejected. The workflow will live with the authentication service code, while metadata changes are issued through a versioned interface rather than a second repository’s manual deployment. A single change record will capture current and next fingerprints, timestamps, the observed fleet distribution, provider checks, approver identity, and recovery options. Operators can pause safely in any compatible state.

        Observability work is equally important. Dashboards will display signature count and failure rate by fingerprint, provider, region, and application version. The main alert will link directly to that breakdown and annotate recent rotation-state changes. The refresh controller will report desired versus observed secret versions for each instance, and the deployment UI will show convergence as a percentage with an explicit list of stale instances. Synthetic tests will cover at least three external providers with different caching behavior. We will add a diagnostic command that takes a failed request identifier and returns the signer fingerprint, advertised certificates at that time, provider metadata age where observable, and the instance configuration version.

        We also need a safe convergence tool. Instead of restarting application processes, the controller will support an authenticated refresh operation with rate limits, progress reporting, and rollback to a compatible key set. It will verify that the target public certificate is already advertised before activating a private key. If an instance fails to refresh, the tool will drain and replace that instance while protecting fleet capacity. The command will be exercised in staging during every rotation and included in the game day. Emergency access will follow the existing audited production path; we are not creating an unreviewed bypass simply because it is convenient during an incident.

        Testing must validate transitions rather than only steady states. We will add integration scenarios where half the fleet remains stale, provider caches range from seconds to hours, metadata requests fail intermittently, and the controller restarts midway through rotation. The invariant is straightforward: every signature produced during a supported state must be verifiable by every certificate set we intentionally exposed. Property-based tests can generate propagation orders and delays to challenge that invariant. The staging game day will then verify the human-facing evidence: responders should recognize a mixed fleet, identify which providers are affected, choose a compatible recovery state, and restore convergence without guessing.

        There are related systems we should audit, but we should stay disciplined. I propose that architecture inventory transitions where two versions can coexist across a trust boundary: encryption-key changes, webhook-secret rotation, event-schema upgrades, and network-policy rollouts. We will score each by blast radius, incompatibility risk, observability, and availability of an overlap mechanism. The incident action is complete when we produce that ranked inventory and assign the highest-risk items, not when every theoretical transition is redesigned. For this authentication issue, I will own the overlap design and state machine. The platform observability lead will own fingerprint telemetry, and the secrets team will own desired-versus-observed reporting.

        My requested decisions are approval to make dual-certificate publication mandatory, agreement that one hundred percent observed convergence is required before retirement, and commitment to run the cross-functional game day before the next production rotation. I will publish a design document within one week, land telemetry within three weeks, complete the automated workflow within five weeks, and use week six for the exercise and any corrections. I’ll provide the Engineering Manager with links to code, dashboards, test results, and the game-day record as verification artifacts. The Customer Support Lead will help define synthetic provider coverage and the customer-facing evidence we need. With those changes, slow propagation becomes an expected operating condition rather than an outage trigger.
        """
    )

    static let incidentSupportLead = ExampleExcerpt(
        id: "incident-review-support-lead",
        role: "Customer Support Lead",
        audience: "Engineering Manager, Technical Lead, support, communications, security, and product",
        meeting: "Authentication incident review",
        text: """
        I am {{name}}, the Customer Support Lead for enterprise accounts. I’ll cover how last Thursday’s authentication incident appeared to customers, how support connected the reports to the broader outage, where our communication helped or created uncertainty, and what we need to change before the next certificate rotation. I’ll use the same timeline established by the Engineering Manager and Technical Lead. My focus is the customer decision-making burden: what administrators could observe, what they needed to know, and whether our messages helped them choose a safe next step. Although we found no data exposure, a prolonged inability to sign in is a serious trust event, especially for customers whose own employees and incident teams depend on our status information.

        The first ticket arrived at 9:47 a.m. from an enterprise administrator reporting repeated redirects after identity-provider authentication. A second customer reported an invalid-signature message one minute later, and a third described users reaching a generic login-error page. These cases entered different queues because their wording and account tiers differed. At 9:52 a frontline specialist noticed that all three involved enterprise single sign-on and posted them in our escalation channel. By 9:54 we linked the cases, notified the on-call engineer, and declared a customer-impacting incident. That correlation was an important success: the specialists did not wait for a large ticket count or assume each customer had misconfigured its provider.

        Ultimately, twenty-three enterprise accounts opened cases and three activated their internal severity-one response. The visible symptom depended on the identity provider and the age of its cached metadata. Some users saw an immediate signature error, some looped between our login page and their provider, and some succeeded intermittently because requests reached different signer instances. Existing sessions continued to work, password login remained available where customers had enabled it, and service-token traffic was largely unaffected. Those distinctions mattered to administrators planning continuity, but they were not present in our first public update. Account teams therefore answered the same questions repeatedly through private channels.

        Our first status message said that some users might be unable to log in and that we were investigating. It was accurate, but it was too general to support action. By then we knew the problem was concentrated in enterprise single sign-on and that existing sessions were stable. We did not yet know the certificate mechanism, so caution was appropriate, but caution did not require vagueness. A more useful message would have named the affected access path, advised users not to sign out of working sessions, identified any configured fallback login method, stated that there was no evidence of unauthorized access, and promised the next update time. We should communicate confirmed scope and safe workarounds even while the root cause remains uncertain.

        The regular update cadence worked well. Customers did not have to wonder whether the incident had been abandoned, and the incident commander gave support a short internal note before each public update. Security joined early and gave us precise language distinguishing availability from compromise. However, our internal case macro asked for browser, region, and identity-provider name but not the request identifier, approximate failure time, metadata refresh time, or certificate fingerprint when the provider exposed one. Engineering had to ask follow-up questions in individual tickets. The escalation directory also pointed to a former identity-team alias, delaying specialist participation. These are process defects we can fix without waiting for the deeper engineering work.

        During mitigation, communication became more difficult because the metadata rollback helped some customers and prolonged inconsistency for others. We initially told administrators that recovery was beginning after seeing improvement in aggregate success rate. Several customers continued to fail because their providers cached the opposite certificate state. The message was technically defensible but sounded like a promise of universal recovery. Future updates should describe recovery by segment and acknowledge cache-dependent variation. For example: “Success rates are improving as signing servers converge, but organizations may recover at different times depending on identity-provider metadata caching.” That gives administrators a truthful model without asking them to understand our implementation.

        We also need explicit guidance for workarounds. Support should never advise customers to disable single sign-on, weaken a security policy, or repeatedly change provider metadata without review. For this incident, safe options were to preserve existing sessions, use an already-configured administrator fallback, and delay nonessential sign-outs. Those options vary by customer configuration. We will create a decision tree that separates universally safe guidance from account-specific actions requiring identity or security approval. The incident commander will designate one owner for workaround language, and support macros will link to the current approved version instead of copying text that can drift during the response.

        Customer follow-up is now grouped by impact. The three severity-one customers will receive an account-team call with support, engineering, and security representation. We will confirm the ninety-six-minute window, explain why access was intermittent, state that existing sessions and stored data were unaffected, and share the corrective-action categories approved in this review. The remaining affected enterprises will receive a written summary and an invitation to raise security, contractual, or identity-provider questions. Service-credit decisions will follow contract terms and verified impact rather than ticket volume. We will also contact administrators who reported confusing redirects so product can review whether the login error page should provide clearer recovery information.

        For future incidents, the support intake template will require the organization identifier, identity-provider type, approximate timestamp, affected login path, whether existing sessions work, any provider error text, and a request or trace identifier. The support console should automatically attach recent authentication health and known-incident status so specialists do not manually search several dashboards. Related cases will be clustered by symptom and access method, with a visible link to the incident record. The escalation alias will come from the live on-call schedule. We will test the workflow during the Technical Lead’s staging game day using simulated customer reports that arrive with incomplete and contradictory details.

        Our communication checklist will prompt the incident team for affected function, customer segments, start time, known workarounds, data or security risk, recovery variability, and next update time. It will also distinguish facts from hypotheses and mitigation from prevention. The first message should optimize for recognition and safe action, not for explaining root cause. Later updates can add the technical model once it is stable. Before resolving the incident publicly, support will confirm that success has returned across representative providers and customer tiers rather than relying only on aggregate telemetry. We will maintain a short internal FAQ so account teams give consistent answers about impact, security, credits, and follow-up.

        We should measure whether these changes improve outcomes. During the game day, frontline specialists should connect the first three related cases within five minutes, collect enough evidence for engineering without a second customer contact, and publish a scoped internal brief within ten minutes of declaration. Communications should produce an actionable draft that identifies the access path, session behavior, security status, and next update. After real incidents, we will review time to correlation, completeness of escalation data, duplicate customer questions, private-message volume, and whether any guidance had to be corrected. A macro existing in the support tool is not evidence that the workflow works under pressure.

        What worked deserves to remain visible. Frontline support trusted the pattern they saw and escalated early. Account teams redirected information into the shared incident rather than creating parallel investigations. Communications maintained cadence and did not speculate about a breach. Security gave quick, usable language. Engineering shared uncertainty honestly and avoided a risky fleet-wide restart. The improvements I’m proposing build on those behaviors: better intake, more specific scope, safer workaround governance, segmented recovery language, and structured follow-up. None of them require support to diagnose certificate distribution; they ensure that the right customer evidence reaches the people who can.

        I am asking for three decisions from this review. First, approve the revised incident-intake fields and make them mandatory for authentication escalations. Second, assign communications and support joint ownership of the customer-update checklist, with security reviewing the risk language. Third, include support and two account-team representatives in the certificate-rotation game day so we test the complete response. I will deliver the intake template and decision tree within two weeks, the communication checklist within three, and the customer follow-up summary this week. I’ll provide completion evidence to the Engineering Manager and coordinate synthetic provider scenarios with the Technical Lead. Our goal is that the next administrator receives clear scope and safe options before they need to ask.
        """
    )
}
