import Foundation

struct ExampleExcerpt: Identifiable {
    let id: String
    let role: String
    let audience: String
    let meeting: String
    let text: String

    var menuTitle: String { "\(role) — \(meeting)" }
    var wordCount: Int { text.split(whereSeparator: \ .isWhitespace).count }

    static let all: [ExampleExcerpt] = [productLaunch, enterpriseDiscovery, incidentReview]

    static let productLaunch = ExampleExcerpt(
        id: "product-launch",
        role: "Senior Product Manager",
        audience: "B2B SaaS leadership and cross-functional launch team",
        meeting: "Launch readiness review",
        text: """
        Thanks, everyone, for making time. I want to use today’s launch readiness review to make a clear go or no-go decision for the workflow automation release scheduled for next Tuesday. I’ll start with the customer problem and the promise we are making, then cover product quality, operational readiness, enablement, and the decisions we still need from this group. The short version is that I believe we are on track to launch, but there are two conditions we should close before Friday: final approval of the migration messaging and a documented support escalation path for customers whose legacy rules behave differently after conversion. Everything else is either complete or has a contained mitigation.

        The customer we designed this for is an operations leader at a mid-market software company with roughly two hundred to two thousand employees. Their teams use our platform across sales, customer success, finance, and internal operations, but their current workflows depend on manual handoffs. They are not asking for a general-purpose programming environment. They want to automate routine decisions without involving engineering every time a field changes or a new approval step is added. The specific job is simple to describe: when a business event happens, evaluate a set of conditions, take the right actions, and make the outcome visible. Today they approximate that with saved views, reminders, spreadsheets, and people who remember the exceptions. The cost is delay, inconsistency, and limited auditability.

        Our release introduces a visual rule builder, reusable action templates, test mode, execution history, and role-based permissions. The launch promise is that an operations manager can automate a common cross-team process in under thirty minutes and can understand why every run succeeded or failed. We should hold ourselves to that statement in every demo and every piece of copy. We are not promising that every historical customization can be recreated with one click. We are promising a safer and much more transparent way to automate the highest-frequency workflows. That distinction matters because early design partners were most satisfied when we framed the product around control and observability, not around an unlimited catalog of triggers.

        On adoption signals, the private beta included twenty-six organizations. Twenty-two created at least one active workflow, seventeen created three or more, and twelve had a workflow running every business day. Median time from opening the builder to a successful test run was twenty-three minutes, which is inside our target. The strongest use cases were lead routing, renewal approvals, onboarding checklists, and finance review. The weakest use case was bulk record cleanup, mostly because customers expected spreadsheet-style transformations that are not part of this release. We changed the empty state and template language so that the boundary is clearer. We also added a link to the bulk editing tool when the system detects that the user may be trying to perform a one-time cleanup rather than create an ongoing automation.

        Product quality is in good shape. We have no open severity-one defects and one open severity-two defect. That issue affects workflows with more than forty branches when the browser window is narrow. The canvas can jump to the wrong position after a branch is reordered. The underlying workflow remains correct, and reopening the editor restores the view. The team has a fix in review, and we expect it to land tomorrow. If it slips, we can still launch with a known-issue note because it affects fewer than one percent of beta workflows and does not corrupt data. Our regression suite now covers template creation, permission changes, test runs, activation, retries, and execution-history filtering. We also completed load testing at three times the projected first-quarter volume.

        The migration experience deserves more attention. Existing customers with legacy notification rules will see a guided conversion option. The converter handles the common cases, but it cannot translate rules that call deprecated webhooks or depend on account-specific scripts. In those cases, it leaves the original rule active and explains what needs manual review. That behavior is safe, but the current message sounds more alarming than it needs to. Legal, support, and product marketing have proposed different versions. My recommendation is that we say, “This rule will keep running in its current form. Review the highlighted steps before moving it to workflows.” That is accurate, direct, and does not imply that the customer must act immediately. I need final agreement on that wording by Thursday afternoon.

        On reliability and operations, the service has met its beta target of 99.95 percent successful executions, excluding customer configuration errors. We added queue isolation so that a single customer cannot consume all workers, and we now cap automatic retries for endpoints that return permanent client errors. The on-call dashboard shows execution latency, queue depth, provider errors, and retry volume by tenant. Alerts route to the platform rotation, with the workflow team as secondary. The remaining gap is the handoff from frontline support when a customer reports an unexpected outcome. Support has the tools to find an execution, but the escalation template does not yet require the workflow identifier, run identifier, and expected result. Without those fields, engineering loses time reconstructing context. I propose we make that template mandatory before launch and run a thirty-minute drill with support on Friday.

        Security and compliance reviews are complete. Workflow definitions are encrypted under the same controls as the underlying customer records. Execution history respects the source object’s retention policy, and secrets used in outbound actions are stored through our existing credential vault. Administrators can restrict who creates, edits, activates, and views workflows. Audit events cover all of those actions. One beta customer asked for approval chains in which one person authors a workflow and another person activates it. That is a valid enterprise requirement, but it is not in this release. We have documented it as a follow-up and trained sales not to position the current permission model as a full separation-of-duties system.

        Go-to-market readiness is mostly complete. Product marketing has the announcement draft, launch page, two-minute overview video, and comparison guide. Sales engineering has a demo workspace with four scenarios that reset automatically. Customer success has identified forty accounts that are strong candidates for guided adoption. The first webinar is scheduled for the week after launch, which gives us time to collect questions from the initial rollout. Pricing does not change with this release; workflow usage counts against existing automation limits. We should say that plainly because several beta participants assumed the feature required a new add-on. The documentation team has published the core concepts, quick start, template catalog, troubleshooting guide, and API action reference to staging.

        Our rollout plan uses three stages. On Tuesday morning, we enable the feature for internal workspaces and the original beta cohort. After two hours of clean telemetry, we expand to ten percent of eligible accounts. On Wednesday, assuming execution success and support volume stay within thresholds, we move to fifty percent. General availability follows Thursday morning. The automatic pause criteria are an execution failure rate above one percent for fifteen minutes, queue latency above five minutes, any confirmed cross-tenant data exposure, or more than ten support cases describing the same unexpected behavior. The release manager can pause without executive approval. Resuming after a pause requires sign-off from engineering, product, and support.

        Success over the first thirty days will be measured with a focused scorecard. The primary adoption metric is the number of organizations with at least one workflow that runs successfully on three separate days. Creation alone is too weak because customers can experiment without receiving value. We are targeting eight percent of eligible organizations in the first month. Our quality measures are successful execution rate, median time to first successful test, and the percentage of disabled workflows caused by configuration errors. We will also track support contacts per one hundred active organizations and review the themes weekly. For longer-term value, we will interview customers about time saved and process consistency, but we should not pretend that we can infer those outcomes from clickstream data in the first month.

        There are three risks I want this team to keep visible. First, templates could make setup look easier than ongoing ownership actually is. We mitigate that with named owners, clear execution history, and reminders when a referenced field is removed. Second, customers may activate high-volume workflows without understanding their usage limits. We now estimate monthly executions before activation and warn at eighty percent of the plan allowance. Third, successful adoption may create more demand for connectors than the integrations team can absorb. We have ranked connector requests by customer reach and will publish criteria rather than responding to the loudest individual account. None of these risks should block launch, but each needs an owner and a review date.

        I’d like to close with the decisions. First, are we aligned that the severity-two canvas issue can ship if the fix misses tomorrow, with a known-issue note and support guidance? My recommendation is yes. Second, can legal, support, and marketing designate one owner to finalize the migration sentence by Thursday at three? My recommendation is product marketing owns the final edit, with legal approving accuracy. Third, can support operations commit to the escalation template and Friday drill? If those decisions land today, I recommend go for the staged release next Tuesday. I will send a written recap with owners, thresholds, and the rollout checklist immediately after this meeting, and we will use Monday’s checkpoint only for exceptions rather than replaying the entire review.
        """
    )

    static let enterpriseDiscovery = ExampleExcerpt(
        id: "enterprise-discovery",
        role: "Enterprise Account Executive",
        audience: "CIO, operations, security, and procurement at a multi-location services company",
        meeting: "Executive discovery call",
        text: """
        Thank you for bringing the broader team together. My goal for this conversation is not to walk through a generic product deck. I want to understand how work moves across your locations today, where the current process creates risk or delay, and what a successful change would need to look like for operations, technology, security, and the people doing the work. If we discover that the problem is a fit for our platform, we can agree on a focused validation plan. If it is not, I will say that clearly. I have sixty minutes reserved. I suggest we spend the first forty on your current state and priorities, ten on the outcomes customers typically achieve, and the last ten on decisions and next steps. Does that match what everyone needs from today?

        From the conversations with Maya and Jordan, my understanding is that your organization has grown to just over one hundred and eighty service locations through a mix of organic expansion and acquisitions. Each location delivers the same core customer promise, but the operational systems and habits differ. Regional managers receive performance data through emailed spreadsheets, local teams open service requests through several channels, and headquarters cannot always see whether an issue is delayed because of staffing, inventory, approval, or incomplete information. The executive concern is not simply that there are too many tools. It is that the tools do not create a dependable operating rhythm. Please correct anything I have misunderstood, and tell me which part creates the most material business impact.

        I would like to start with the moment a frontline employee identifies an exception: a customer escalation, an equipment problem, a staffing gap, or a quality concern. What happens next in the best case, and what happens on a difficult day? Who decides the priority? Which details must be present before another team can act? How do people know who owns the next step? I am especially interested in the work that takes place outside the official system, because text messages, personal spreadsheets, and hallway conversations often reveal where the designed process does not match reality. There is no judgment in that question. Informal tools usually emerge because committed people are compensating for friction. We want to understand the friction before proposing software.

        The second area is management visibility. When an executive asks on Tuesday morning which locations are at risk of missing a service-level commitment by Friday, how is that answer produced? Is the data available continuously, or does someone assemble it? How confident are you that two regional leaders define an at-risk location the same way? What actions follow the report? Many organizations have dashboards that accurately describe last week but do not help a manager intervene today. The distinction matters. If the objective is faster operational response, we should validate whether the platform can connect a signal to a named action, owner, and deadline rather than simply offering another place to view metrics.

        Third, I want to understand variation across locations. Some variation is waste, but some reflects different regulations, customer mixes, staffing models, or facility constraints. A central program can fail if it treats every local difference as noncompliance. How do you decide which steps must be standard and which can be configured regionally? Who has authority to approve an exception? How often do local teams create their own version of a headquarters process because the standard one is too slow? Our strongest deployments establish a small set of common data and controls while allowing defined local choices. If your goal is absolute uniformity from day one, we should examine whether that is operationally realistic before we scope technology.

        Let’s also discuss the people affected. How many frontline employees, location managers, regional leaders, and headquarters specialists would interact with the system? What devices do they use during a shift? Are shared workstations common? How frequently do employees change roles or locations? What languages and accessibility needs must be supported? Adoption problems often appear when a workflow designed on a large office monitor reaches someone using a phone with gloves on, limited connectivity, and a customer waiting. We can demonstrate a clean interface, but the validation should include actual users in actual conditions. I would recommend that any pilot include at least two high-performing locations, two average locations, and one location that has struggled with the current process.

        On technology, I understand that your system of record for customer and location data is Dynamics, identity is managed through Entra ID, and the data platform is Snowflake. There are also two scheduling systems inherited through acquisitions. Which system should be authoritative for employee, location, and service-request data? Where do identifiers fail to match? Are integrations currently real time, scheduled, or manual? We should be careful not to label every connection as a simple integration. If the same location has different codes across three systems, the hard work is governance and mapping, not moving bytes. Our technical team can help document that, but your data owners will need to make decisions that software cannot make for them.

        Security and compliance need to be part of discovery rather than a gate at the end. What categories of personal, customer, financial, or regulated data would enter the platform? Are there regional residency requirements? What are your expectations for single sign-on, automated provisioning, role review, audit exports, encryption, retention, incident notification, and business continuity? We can provide our security package after this call, including architecture, control reports, penetration testing summary, subprocessors, and standard data-processing terms. More important, I would like your security lead to identify any nonstandard requirement early. If there is a control we cannot meet, both sides should know before investing in a pilot.

        The business case should begin with a baseline we trust. You mentioned that regional teams spend substantial time collecting updates and chasing incomplete requests. Can we estimate the number of requests per month, average handling time, percentage returned for missing information, and hours spent preparing management reports? We should also quantify the cost of delay: missed service commitments, repeat visits, customer credits, overtime, or preventable equipment downtime. I do not want to build a case by multiplying every employee by a speculative number of minutes. A credible case uses a few observable processes, conservative assumptions, and ranges. If the main value is risk reduction or customer consistency rather than labor savings, we should name that instead of forcing everything into headcount.

        Based on what I have heard so far, a sensible first use case may be the service-exception workflow. It crosses locations and headquarters, has measurable delays, and does not require replacing the core scheduling system. A request would begin with a guided intake, enrich itself with customer and location data, route according to severity and region, track ownership, escalate against agreed timers, and produce a consistent history for analysis. The pilot would not attempt every exception type. We might select two categories that represent meaningful volume and different routing patterns. That scope is large enough to test integration, permissions, mobile use, reporting, and governance without turning the pilot into a disguised enterprise rollout.

        For success criteria, I would propose five measures for discussion. First, reduce requests returned for missing information by at least thirty percent. Second, reduce median time to an acknowledged owner by twenty-five percent. Third, give regional managers a current view of aging and risk without manual spreadsheet consolidation. Fourth, achieve weekly active use by at least eighty percent of participating managers and frontline users during the final two pilot weeks. Fifth, complete the pilot without a critical security or integration defect. We should establish baseline definitions before configuration begins and agree on who validates the results. If your team has board-level or customer-level commitments tied to this initiative, those may change the measures.

        I also want to be transparent about effort. Our platform is configurable, but a successful deployment still requires process ownership, integration decisions, testing, training, and change management. We would provide a solution architect, implementation lead, customer success manager, and training resources. From your side, we would need an executive sponsor, a day-to-day program owner, process experts, an identity administrator, integration support, security participation, and representatives from pilot locations. For the focused use case I described, discovery and design usually take two to three weeks, configuration and integration four to six weeks, and a measured pilot four weeks. Those are planning ranges, not a commitment before technical validation.

        Commercially, it is too early to put a final proposal in front of you because user population, workflow volume, environments, and service requirements are not yet confirmed. I can provide a transparent planning range after we define the pilot and likely rollout population. Procurement often asks for a fixed number before discovery, but false precision creates frustration later. We can separate the pilot services, subscription assumptions, optional implementation support, and any usage-based components so you can see what changes the price. I would also like to understand your budgeting window, approval path, contracting requirements, and whether another initiative competes for the same people or funds.

        To close, let me reflect the emerging decision. You are evaluating whether a shared workflow layer can improve consistency and response time across acquired locations without forcing an immediate replacement of every operational system. The likely validation is a service-exception pilot across five representative locations, integrated with identity and the primary customer system, measured against completeness, ownership speed, manager visibility, adoption, and technical risk. The open questions are data ownership, security exceptions, pilot staffing, and the baseline economics. If that summary is accurate, I suggest a ninety-minute working session next week with operations, IT, security, and two location leaders. We will arrive with a draft process map and validation plan, and your team can challenge both. After that session, we should be able to decide together whether a pilot is justified and what it would take to execute responsibly.
        """
    )

    static let incidentReview = ExampleExcerpt(
        id: "incident-review",
        role: "Engineering Manager",
        audience: "Engineering, SRE, support, security, and product leadership",
        meeting: "Production incident review",
        text: """
        Thanks for joining. This is the review for last Thursday’s authentication incident. Our purpose is to understand the system conditions and decisions that allowed the outage, agree on changes that reduce the chance and impact of recurrence, and make ownership explicit. This is not a performance review of the individuals who responded. People acted with the information, tools, and incentives available at the time. If our conclusion is simply that someone should have noticed sooner or typed a different command, we will have missed the organizational and technical lessons. I’ll cover customer impact, the timeline, contributing factors, what worked, what did not, and the actions I recommend. Please interrupt when a fact is wrong, but let’s separate factual corrections from solution debate until we reach the action section.

        The incident began at 9:42 a.m. Pacific and customer impact ended at 11:18 a.m., for a total of ninety-six minutes. During that period, approximately thirty-eight percent of interactive login attempts failed. Existing sessions remained valid, and API traffic using long-lived service credentials was mostly unaffected. The highest impact was on customers whose identity providers require signed authentication requests. Users saw either a generic login error or repeated redirects. Twenty-three enterprise accounts opened support cases, and three customers activated their internal severity-one process. We have no evidence of unauthorized access, data exposure, or lost writes. The incident affected availability and trust, not confidentiality or integrity, but the user experience was severe enough to warrant our highest operational classification.

        The initiating change was a routine certificate rotation for the service that signs outbound single sign-on requests. We rotate these certificates every ninety days. At 9:15, the identity team deployed a new certificate to the secrets store and updated the signer configuration. The change passed the automated deployment checks, and canary requests using our internal identity provider succeeded. At 9:37, a background refresh began across the authentication fleet. Some instances loaded the new certificate and others retained the old one because the refresh operation is asynchronous and has no fleet-wide completion signal. At 9:42, metadata advertised the new public certificate globally. Identity providers that refreshed metadata immediately began validating against the new certificate, while requests from instances still holding the old private key failed signature validation.

        Our first alert fired at 9:46 for elevated login error rate. The on-call engineer acknowledged it at 9:48 and began checking the authentication service. The aggregate dashboard showed an increase in external identity-provider errors but did not group failures by signing certificate fingerprint. At 9:54, support linked the first three enterprise cases and declared a customer-impacting incident. The incident commander joined at 10:01. The team initially suspected a regional identity-provider issue because failures varied by customer and requests from our internal provider continued to pass. At 10:17, an engineer compared a failed signed request with current metadata and found the fingerprint mismatch. At 10:24, the team decided to roll metadata back to the previous public certificate.

        The rollback did not immediately resolve the issue. Several identity providers had already cached the new metadata and would not fetch the old certificate again for up to an hour. At 10:31, the team considered forcing every signer instance to the new private key, but we lacked a safe command to verify completion across the fleet. Engineers used the deployment system to restart instances in controlled batches, which caused each replacement to load the new certificate. At 10:52, telemetry showed that more than ninety-five percent of signatures used the new fingerprint, and login success began recovering. The last stale instance left service at 11:07. We continued monitoring through 11:18, when error rates returned to baseline across customer segments. We published resolution at 11:25 and sent targeted follow-up to affected enterprise administrators that afternoon.

        The direct technical cause was an unsafe ordering between private-key rollout and public-certificate advertisement. The system treated those operations as independent eventually consistent changes, but the protocol requires a coordinated transition. The certificate rotation runbook assumed that secret refresh completed within five minutes because that had been true in previous rotations. It did not define a measurable completion condition. The deployment check proved that new instances could sign with the new key, not that all serving instances had stopped using the old key. Finally, metadata exposed only one active verification certificate. If we had advertised both old and new certificates during an overlap window, identity providers could have accepted requests from either fleet state.

        Several contributing factors increased duration. Our synthetic login checks use the internal identity provider, which refreshes metadata quickly and happened to receive requests signed by updated instances. The alert grouped all external provider failures together and did not display certificate fingerprints, so the pattern looked like a provider-specific problem. Ownership for metadata publishing and signer deployment is split across two repositories and two teams, with no single automated workflow coordinating them. The rollback procedure was designed for application code, where returning to the previous version restores compatibility. Certificate distribution involves external caches, so reversing metadata can create a second inconsistent state. The incident channel also lacked an identity-provider specialist for the first twenty minutes because the escalation directory listed a former team alias.

        It is important to note what worked. The customer-impact alert detected the issue four minutes after the first failures, well inside our ten-minute objective. The on-call engineer acknowledged promptly and opened a shared investigation. Support recognized related cases and escalated without waiting for account teams. Once the fingerprint mismatch was identified, engineers resisted the temptation to restart the entire fleet at once and used batches to protect existing sessions. Security joined early, confirmed that the symptom did not indicate forged requests, and preserved relevant logs. Communications posted updates on a regular cadence even when the technical diagnosis was incomplete. No one concealed uncertainty, and the incident commander kept a decision log that made this reconstruction much easier.

        Our customer communication had one weakness. The first status message said that “some users may be unable to log in,” which was accurate but not useful for administrators deciding whether to activate their continuity plans. We knew by then that the issue was concentrated in enterprise single sign-on, while password and service-token access remained available. A more actionable update would have identified the affected access path, confirmed that existing sessions continued, and stated that there was no evidence of a security breach. We were cautious because diagnosis was evolving, but caution does not require vagueness. Communications and support will add incident-specific prompts so the commander considers audience, affected function, available workaround, data risk, and the next update time.

        The first corrective action is to redesign certificate rotation as an overlap protocol. At least twenty-four hours before using a new signing key, metadata will publish both the current and next public certificates. We will verify that representative identity providers have fetched the dual-certificate metadata. The signer fleet will then move to the new private key, with telemetry proving that one hundred percent of active instances use the expected fingerprint. The old certificate will remain advertised for a defined cache-expiration window before removal. This is the standard pattern supported by the protocol, and it turns a synchronized cutover into a compatible transition. Priya will own the design, with implementation targeted for the next rotation in six weeks.

        The second action is to automate evidence and guardrails. The deployment pipeline will block metadata removal unless fleet telemetry shows no signatures from the retiring key for twenty-four hours. It will run synthetic authentication against three external test identity providers with different caching behavior. Dashboards will break down signature failures by provider, region, application version, and certificate fingerprint. The secrets refresh controller will report desired and observed versions for every instance instead of emitting only a successful request event. We will also create a safe fleet refresh command that can converge configuration without requiring a full application deployment. Mateo owns the observability work, and Chen owns the controller changes.

        The third action addresses operational design. We will consolidate the signer and metadata steps into one versioned runbook generated from the automation itself. A single change ticket will name an end-to-end owner, reviewer, verification window, and rollback strategy that accounts for external caches. The identity escalation alias will be generated from the current rotation schedule rather than maintained manually. Before the next production rotation, the team will run a game day in staging that intentionally leaves part of the fleet stale, advertises multiple certificates, simulates a provider with a long cache, and practices recovery. Support and communications will participate so the exercise tests the complete response rather than only the technical mechanism.

        We also need to discuss the risk of similar assumptions elsewhere. Certificate rotation is one example of a broader class: distributed configuration changes in which producers and consumers do not update atomically. Feature flags, encryption keys, webhook secrets, schema versions, and network policies can fail in comparable ways. Architecture will lead a two-week review to identify transitions that currently depend on an undocumented propagation delay or a single active version. The output should not be a giant backlog of hypothetical concerns. We will prioritize changes where an incompatible intermediate state can create broad customer impact and where an overlap, version handshake, or observable convergence check is feasible.

        For accountability, each action has an owner and a verification artifact. We will not mark “improve monitoring” complete because a dashboard exists; it is complete when an alert exercised in staging links directly to the fingerprint breakdown and an on-call engineer can identify the mixed fleet within five minutes. We will not mark the new runbook complete because a document is merged; it is complete when the game day follows it successfully and participants record no ambiguous decision points. Product and support will review customer follow-up with the three most affected accounts, and we will track whether they need security documentation, service credits, or an executive conversation. The incident remains open until the high-priority actions pass verification.

        My final assessment is that the outage was preventable, but not because one person ignored an obvious instruction. Our system encoded a timing assumption where it needed a compatibility protocol and an observable state transition. Our tests validated the destination but not the journey. Our rollback model did not account for external caches. The response team mitigated responsibly once the failure mode was understood. The right outcome is to build a rotation process that stays safe when refresh is slow, caches are unpredictable, and humans are under pressure. If there are no factual corrections, I would like approval of the three high-priority action groups, their owners, and the six-week deadline. I will publish the review, decision log, and action tracker today, with a progress check in two weeks and a game-day readout before the next production rotation.
        """
    )
}
