import Foundation

extension ExampleExcerpt {
    static let launchProductManager = ExampleExcerpt(
        id: "meeting-assistant-launch-product-manager",
        role: "Product Manager",
        audience: "Engineering Lead, Privacy & Security Lead, Customer Success Lead, design, analytics, and operations",
        meeting: "AI meeting assistant launch readiness",
        text: """
        I am {{name}}, the Product Manager for Decision Digest, our AI meeting assistant. I am facilitating today’s launch-readiness review so we can make a clear decision about the September fifteenth general-availability target. I’ll summarize the customer problem, pilot evidence, scope, success measures, and decisions that still need owners. Our Engineering Lead will cover reliability and rollout controls, our Privacy and Security Lead will review consent and data handling, and our Customer Success Lead will explain operational readiness and customer expectations. The objective is not to defend the date. The objective is to decide whether we can launch a useful, trustworthy product with measurable guardrails, and to be explicit about any conditions that would change that decision.

        Decision Digest turns a completed video meeting into a structured summary containing decisions, action items, open questions, and links back to transcript timestamps. The product is aimed first at project teams that already record internal planning meetings but lose time reconstructing commitments afterward. Twenty-four design partners have used the pilot for eight weeks, representing roughly eighty-four hundred eligible employees and about thirty-two thousand processed meetings. Activation is strong when a workspace administrator enables the feature and explains the consent model. Weekly retention among people who opened at least three digests is sixty-eight percent, and those users report saving an average of fourteen minutes per meeting. The value is real, but those headline numbers do not by themselves establish launch readiness.

        The quality picture is encouraging and uneven. Human reviewers rated eighty-nine percent of decision statements as fully supported by the transcript and another seven percent as directionally correct but missing context. Action-item extraction reached ninety-two percent precision and eighty-one percent recall. The misses cluster in meetings with rapid speaker changes, indirect commitments, or mixed languages. In the pilot, two summaries assigned an action to the wrong person and one converted a tentative proposal into a final decision. No customer acted on those errors before correcting the digest, but these are exactly the mistakes that can damage trust. For general availability, the digest must remain visibly editable, every statement must link to source context, and the interface must describe the output as a draft rather than an authoritative record.

        Our proposed launch scope is intentionally narrower than the full vision. General availability will support scheduled internal meetings in English, Spanish, French, and German. It will require an organization administrator to enable the capability, a meeting organizer to turn it on, and an in-meeting notice visible to every attendee. External meetings, webinars, regulated-workflow templates, automatic task creation, and coaching scores remain excluded. Digests will be generated only after the meeting ends, and nothing will be sent automatically to task systems or email lists. Organizers can review, edit, or delete a digest before sharing. This boundary preserves the core time-saving experience while avoiding irreversible downstream actions during the first release.

        I want to separate launch gates from follow-up improvements. A launch gate protects a promise that appears in the product or our customer agreement. Before release, we need transcript-grounding links on every generated item, reliable attendee notice, deletion propagation within the documented window, workspace-level disable controls, and rollback that stops new processing without losing original meeting data. We also need the ninety-fifth-percentile digest time below fifteen seconds for a sixty-minute meeting, because the product experience implies the result is available immediately after the call. Custom summary styles, more languages, mobile editing, and direct integrations are valuable, but they are not required to safely deliver the initial promise.

        The current readiness dashboard shows three yellow areas. First, ninety-fifth-percentile generation time is fourteen point eight seconds, leaving almost no margin against the fifteen-second objective. Engineering has a batching change ready that should reduce this to eleven seconds, but it has only been tested against replay traffic. Second, the administrative audit log records feature enablement and digest deletion but does not yet record export. Privacy and Security consider export visibility part of the enterprise control story. Third, support documentation covers common behavior but not a meeting where one participant withdraws consent after recording. Customer Success has drafted a response path, and we need the product behavior and policy language to match it before enablement expands.

        The rollout plan is a staged availability process, not a single global switch. In week one, we will invite five existing design partners that have completed the revised administrator checklist. In week two, we can expand to twenty-five organizations if latency, grounded accuracy, consent-notice delivery, deletion completion, and support volume stay inside thresholds. A five-percent self-service cohort follows in week three, with increases to twenty-five, fifty, and one hundred percent separated by at least three business days. The feature flag can disable new digest generation by organization, region, or meeting type. Previously generated digests remain accessible unless the customer deletes them, which avoids making recovery more disruptive than the original problem.

        Success will be measured as a balanced scorecard. Adoption means at least thirty-five percent of eligible meetings produce a digest and at least half of those digests are opened. Utility means thirty-day retained usage above fifty percent and a customer-reported time saving above ten minutes per used meeting. Trust means fewer than one substantiated unsupported-decision report per thousand digests, no notice-delivery failures, deletion completion above ninety-nine point nine percent within the stated window, and fewer than three support contacts per hundred enabled workspaces during the first month. Reliability means a successful generation rate above ninety-nine point five percent and ninety-fifth-percentile completion under fifteen seconds. We will not trade away trust metrics to improve adoption.

        We also need clear launch communications. Marketing can say that Decision Digest creates an editable, transcript-linked draft of decisions and action items. It cannot claim perfect notes, legal-grade minutes, or automatic compliance. Sales must use the approved capability matrix for supported languages, retention, regional processing, and administrative controls. In-product education should show how to verify an item against the transcript and how to correct attribution. The launch blog and help center should explain that the meeting organizer controls generation but that every attendee receives notice. If our public message is more confident than the product’s actual safeguards, support will spend the launch correcting expectations instead of helping customers adopt it.

        There are four decisions I want from this room. First, do we agree that export audit logging is a launch gate rather than a post-launch enhancement? My recommendation is yes because enterprise administrators use the audit record to investigate where meeting content went. Second, can the latency optimization graduate after a forty-eight-hour production-shadow test, or do we require a full week? I recommend forty-eight hours if replay, fault-injection, and canary results all pass. Third, do we keep four-language support at launch if German action-item recall remains six points below English? I recommend keeping it with a visible beta label for non-English summaries and a language-specific quality threshold. Fourth, who has final authority to pause expansion? I recommend the launch commander, with Engineering, Privacy, or Customer Success each able to trigger a hold.

        Ownership must be unambiguous. Engineering owns the batching change, regional kill switch, generation reliability, and the telemetry proving each gate. Privacy and Security own the consent verification, export audit requirement, retention validation, and incident escalation criteria. Customer Success owns administrator enablement, support training, escalation routing, and the daily voice-of-customer summary. Product owns scope, customer-facing claims, the readiness dashboard, and the written go or no-go record. Analytics will sample digest quality by language and meeting type. Every gate needs a link to evidence, not a verbal assurance. If a result is unavailable, the gate is not green.

        My current recommendation is a conditional go for the five-customer cohort, not approval for unrestricted general availability. The conditions are that the export event appears in the audit log, the latency canary stays below twelve seconds at the ninety-fifth percentile, the consent-withdrawal procedure is tested end to end, and all four functions sign the launch record. If any trust metric crosses its stop threshold, expansion pauses automatically while the current cohort remains supported. We reconvene after the first five hundred production digests to review quality, support demand, and privacy events. This gives customers genuine value while keeping the cost of learning bounded.

        To close, I want us to leave with one shared narrative. We are launching a reviewable assistant, not an autonomous source of truth. The product succeeds when it reduces administrative work and makes evidence easier to find without hiding uncertainty or weakening participant control. We have enough pilot evidence to begin a controlled rollout, provided we complete the remaining controls and respect the stop conditions. I will publish today’s decision log by the end of the day, update the launch checklist with named owners and dates, and schedule the five-hundred-digest review. I’m asking each lead to confirm whether the proposed conditions are sufficient and to name any fact that would cause you to recommend no-go.
        """
    )

    static let launchEngineeringLead = ExampleExcerpt(
        id: "meeting-assistant-launch-engineering-lead",
        role: "Engineering Lead",
        audience: "Product Manager, Privacy & Security Lead, Customer Success Lead, platform, machine learning, and SRE",
        meeting: "AI meeting assistant launch readiness",
        text: """
        I am {{name}}, the Engineering Lead for Decision Digest. I’ll describe the production architecture, the evidence behind our reliability claims, the remaining latency work, and the controls we will use during the staged launch. I’ll use the same scope the Product Manager proposed: post-meeting digests for scheduled internal meetings, with four supported languages, explicit enablement, attendee notice, transcript-grounded output, and no automatic downstream actions. My recommendation is a conditional go for the five-customer cohort, provided the batching canary and export audit event pass before enrollment. I do not recommend opening the self-service cohort until we have observed at least five hundred production digests and completed one rollback exercise.

        The processing path begins when the meeting service emits a completion event containing the recording and transcript identifiers, organization policy version, participant-notice result, language, and regional routing key. An admission service verifies that the organization and organizer enabled Decision Digest, that notice succeeded, and that the meeting type is in scope. It then writes a durable job without copying media. Workers retrieve the transcript from its source region, divide it into overlapping semantic windows, generate candidate decisions and actions, and run a grounding pass that requires a timestamp range for every item. A final assembler removes duplicates, preserves uncertainty labels, and writes the digest back to the meeting record. The worker never needs access to unrelated meetings or the customer’s task systems.

        Reliability during the pilot was ninety-nine point six two percent successful completion across thirty-two thousand jobs. Most failures were transient model-provider timeouts and were recovered by bounded retry. Twelve jobs required manual replay after a regional queue configuration was deployed with the wrong concurrency limit. We have since moved queue limits into the versioned service configuration and added a deployment check that compares desired and observed values by region. Jobs are idempotent: a retry uses the same job identity and replaces an incomplete draft instead of creating duplicates. The dead-letter queue alerts after three failed attempts, and the operator view shows the policy version, processing region, error category, and safe replay action without exposing transcript content in logs.

        Latency is the main engineering risk. Median generation is six point two seconds for a sixty-minute meeting, but the ninety-fifth percentile is fourteen point eight seconds and the ninety-ninth percentile reaches twenty-seven seconds. Profiling shows that long transcripts create many small inference requests, increasing queue overhead and reducing cache efficiency. The batching change groups compatible transcript windows while preserving organization and region isolation. Replay against the last ten thousand pilot jobs reduced the ninety-fifth percentile to ten point nine seconds and the ninety-ninth percentile to seventeen point four seconds, with no statistically significant quality regression. Before launch, we will run it in shadow mode for forty-eight hours, compare output hashes and grounding scores, then enable it for one internal canary organization.

        Capacity planning assumes the first cohort produces twenty thousand meetings per week, with a fivefold peak during weekday afternoons. The current regional pools can handle eight times that initial peak while keeping thirty percent headroom, but shared model-provider quotas are a possible bottleneck. We have reserved capacity for the first two rollout stages and implemented per-organization fairness so one large import cannot starve interactive jobs. When saturation approaches, admission will queue work and show a delayed status rather than dropping jobs or routing content outside the configured region. The kill switch stops new admissions immediately and lets in-flight jobs either finish or move to a policy-defined cancellation state. We will test both paths before launch.

        Grounding is implemented as an enforceable output contract. Every decision and action must include at least one transcript span, speaker attribution when available, and a confidence category. An unsupported item fails assembly and is omitted. The user interface can still expose the transcript segment even if speaker diarization is uncertain. We monitor unsupported-candidate rejection, attribution correction, edit distance, and user deletion by language. Quality samples are reviewed blindly each week, and any substantiated unsupported decision opens a severity review. The system prompt and model version are recorded with the digest so we can reproduce behavior. Model changes use the same staged rollout as application changes and cannot bypass the quality suite.

        The four-language launch requires separate evidence. English and Spanish exceed the agreed precision threshold. French is within two points of English. German action-item recall is lower because modal phrasing is often interpreted as discussion rather than commitment. Precision remains high, so the system is not inventing more actions; it is omitting some. We have added language-specific examples and a classifier change that improves replay recall by four points. I support the Product Manager’s proposal to label non-English summaries as beta, but only if the readiness dashboard remains segmented. Aggregate metrics can conceal a language regression, and expansion should pause for the affected language without disabling healthy regions or English processing.

        Data deletion is designed as an event-driven workflow. Deleting a meeting or digest creates a signed deletion request that removes the digest, derived embeddings, temporary transcript windows, and cached inference artifacts. Each subsystem acknowledges completion, and the control plane reports whether the documented deletion window was met. Pilot tests completed ninety-nine point nine eight percent within fifteen minutes; the longest took forty-one minutes after a worker outage, still inside the customer commitment. This week we added reconciliation that compares source meeting state against derived records, so a missed event is repaired. The launch test will delete one meeting during processing, one after sharing, and one after a participant withdrawal request to verify the full chain.

        The export audit event is small in code and important in behavior. The download endpoint already authenticates the user and records operational telemetry, but it does not write the customer-visible administrative event required by the new capability matrix. The patch adds organization, actor, digest, meeting, timestamp, and export format without transcript text. It is under review today, with integration coverage for success, denial, and retry. We will deploy it behind the digest flag and have Privacy and Security verify the event in the administrator console. If that evidence is not available by the enrollment cutoff, we should move the cohort date instead of accepting an undocumented control gap.

        Observability and rollback are organized around customer outcomes. The launch dashboard shows admission rate, notice-validation failure, generation success, latency percentiles, grounding rejection, deletion completion, export events, and support-linked organization identifiers. Alerts are segmented by region and language. The launch commander can freeze expansion, disable a language, disable an organization, or stop all new jobs. A rollback does not delete valid existing digests and does not alter source recordings. If a model regression is detected, we can pin the previous model version for new jobs and offer regeneration for affected drafts after customer review. All actions are recorded in the operational timeline.

        We have completed load tests, dependency failure tests, duplicate-event tests, regional isolation tests, and model-provider timeout tests. Two exercises remain. The first is an end-to-end notice failure: we will suppress the attendee notice event and confirm that admission rejects the job, the organizer sees a clear reason, and no transcript is sent to generation. The second is a launch rollback during peak synthetic traffic: we will disable new processing, drain or cancel in-flight jobs according to policy, confirm customer-visible states, then restore from the previous release. Customer Success will observe the exercises because operational messages are part of correctness. Passing means the response can be executed from the runbook without an engineer improvising database changes.

        My owners and dates are as follows. The machine-learning platform owner will finish the batching shadow comparison tomorrow and publish language-level quality results. The application team will merge and deploy export auditing by Thursday. SRE will run the rollback exercise Friday and attach the timeline, alert screenshots, and recovery measurements. The data platform owner will complete the withdrawal deletion test with Privacy on Monday. I will review every artifact and provide a signed engineering readiness statement to the Product Manager. During the first cohort, one engineering lead and one SRE will be assigned each business day, with a fifteen-minute acknowledgment objective for launch alerts.

        In summary, the architecture supports a controlled launch and the known risks are observable and reversible. The two items I consider hard gates are customer-visible export auditing and proof that the latency optimization behaves under live canary traffic. The notice and deletion exercises are also required because they validate promises outside the generation service itself. If those pass, the five-customer cohort is a responsible next step. If they do not, waiting is cheaper than debugging consent, data handling, or capacity behavior across newly enabled organizations. I am comfortable owning the technical go or no-go recommendation and will trigger a hold if evidence contradicts the thresholds we agreed today.
        """
    )

    static let launchPrivacyLead = ExampleExcerpt(
        id: "meeting-assistant-launch-privacy-lead",
        role: "Privacy & Security Lead",
        audience: "Product Manager, Engineering Lead, Customer Success Lead, legal, compliance, and security operations",
        meeting: "AI meeting assistant launch readiness",
        text: """
        I am {{name}}, the Privacy and Security Lead reviewing Decision Digest for launch. My role today is to determine whether the proposed experience gives organizations and meeting participants meaningful control over how their conversation is processed, whether our technical controls match the claims in our documentation, and whether the rollout can be stopped before a small issue becomes a broad trust event. I am not evaluating whether summaries are commercially attractive; the pilot already shows that. I am evaluating whether the feature can deliver that value within clear purpose, access, retention, transparency, and incident-response boundaries. My current position is conditional approval for the five-customer cohort, subject to four evidence items I will describe.

        The allowed purpose is narrow: produce an editable, transcript-linked draft of decisions, action items, and open questions for the completed meeting. Meeting content cannot be used for advertising, employee scoring, generalized model training, or unrelated workspace profiling. The generation provider operates as a processor under our agreement and may not retain prompts or outputs beyond the configured transient window. We send only the transcript segments needed for the current digest, plus speaker labels already visible in the meeting. We do not send participant email addresses, workspace billing data, private chat, or content from other meetings. Any future purpose, especially coaching or cross-meeting analytics, requires a separate review and cannot be introduced through a prompt change.

        Consent and notice require multiple layers because administrator enablement alone is insufficient for a live conversation. An organization administrator first enables the feature and accepts the data-processing terms. The organizer then chooses Decision Digest for a specific meeting. Every attendee receives a persistent in-meeting notice before processing eligibility is established, and the meeting record shows whether that notice was delivered. If delivery fails, generation must not begin. The organizer cannot dismiss the notice on behalf of others, and a hidden background setting cannot silently reactivate the feature. For external or anonymous attendees, which are outside launch scope, admission rejects the job rather than assuming the organizer’s policy extends to them.

        The most important unresolved workflow is a participant who objects after the meeting. Our policy allows that person to request deletion through the organization administrator or our privacy channel. For the launch scope, we will delete the entire derived digest rather than attempt to remove one speaker’s contribution while preserving an output influenced by it. The source recording follows the organization’s separate meeting-retention policy, and our interface must not imply that deleting the digest deletes the source recording. Customer Success has drafted the request procedure, Engineering has implemented deletion propagation for derived data, and Legal has reviewed the wording. We still need one end-to-end exercise proving that the request reaches the correct workspace, triggers the right deletion, and produces a completion record.

        Retention must be understandable. Temporary transcript windows and provider-side request data expire after processing and may remain in encrypted operational backup for no more than the documented recovery period. The digest remains with the meeting until the customer deletes it or the meeting itself expires. Derived embeddings used only to assemble the digest follow the shorter processing retention, not the meeting’s longer retention. Support logs must use identifiers and error categories rather than transcript excerpts. Debug access to content requires an approved customer case, time-limited authorization, and an audit record. The launch runbook will prohibit copying meeting text into general incident channels, ticket titles, or unapproved analysis tools.

        Access control inherits the meeting record’s audience. A user who cannot open the original meeting cannot open or export its digest. When meeting membership changes, digest access changes with it. Organizers may edit the draft, but edits do not grant a wider audience. Shared links use the same organization controls as recordings and can be revoked. The security test covered direct-object references, role changes, expired sessions, cross-organization identifiers, and export authorization. No high-severity finding remains open. One medium finding involving stale link previews was fixed and retested. We will repeat the authorization suite against the release candidate because access behavior is too important to infer from unit coverage alone.

        Export auditing is a launch gate because exporting changes the risk boundary. Reading a digest inside the controlled meeting experience is not equivalent to downloading a portable file. Administrators need to know who exported which digest and when, especially during an investigation or deletion request. The event should contain actor, organization, meeting and digest identifiers, timestamp, result, and format, but no meeting content. Engineering’s proposed event satisfies that design. My team will verify success, denied export, and retried export in the customer-visible audit console. Operational telemetry that only our engineers can query does not satisfy the administrator promise.

        Model quality is also a trust issue, even when it is not strictly a privacy control. A false decision attributed to a named person can affect reputation or workplace action. The launch design mitigates this by calling the output a draft, linking every item to transcript evidence, exposing uncertainty, allowing correction, and preventing automatic task creation. We should avoid anthropomorphic copy that suggests the assistant understood intent. Quality monitoring must look for unsupported claims and incorrect attribution by language, not merely user engagement. If a customer reports a harmful false attribution, support should preserve the minimal evidence, route it through the trust escalation, and avoid broad internal sharing of the meeting.

        Our threat model includes malicious transcript content attempting to redirect the model, a participant speaking secrets aloud, an attacker guessing meeting identifiers, a compromised support account, provider unavailability, and an internal operator using debug tools outside an approved case. Prompt-injection tests confirm that transcript instructions cannot alter the output schema or request external tools. Output is treated as untrusted text and safely rendered. Meeting identifiers are authorization checked, not treated as bearer secrets. Support access is least privilege and time limited. Provider failure results in a failed or delayed digest, not rerouting to an unapproved model. Operator queries are audited and sampled by Security Operations.

        Regional processing claims must match actual routing. The job carries the organization’s region from admission through transcript retrieval, model invocation, derived storage, and deletion. A region mismatch causes rejection and a security alert; it cannot silently fall back to another pool. Pilot routing tests passed for North America and Europe, including retry and dead-letter handling. The first cohort includes customers in both regions so we can verify real operational evidence. Sales must not promise additional residency locations until the full path exists. The capability matrix is the source of truth, and exceptions require Privacy, Security, Legal, and Engineering approval rather than an account-level configuration workaround.

        For monitoring, I require a daily launch report containing notice-delivery failures, jobs rejected for policy mismatch, privileged content-access events, deletion completion, export events, provider retention attestations, and trust-related support cases. A single confirmed job processed without valid notice is a stop condition. A deletion that exceeds the contractual window, an unexplained regional mismatch, unauthorized access, or evidence of provider retention beyond policy also stops expansion and begins incident triage. Lower-severity quality issues may pause a language or organization while investigation continues. These thresholds must be encoded in the launch plan so the team does not debate acceptable risk while an event is unfolding.

        My four approval conditions are concrete. First, the participant-withdrawal exercise must prove intake, identity verification, derived-data deletion, reconciliation, and completion notice. Second, the export event must appear correctly in the customer-visible audit log. Third, the release candidate must pass the authorization and regional-routing suites with no unresolved high-severity finding. Fourth, Product, Customer Success, and Sales must publish one consistent description of supported purpose, languages, retention, reviewability, and limitations. Evidence for each condition will be attached to the launch record, and my team will sign only after reviewing the artifact rather than accepting a status summary.

        With those conditions, I support a bounded five-customer launch because the system is designed to fail closed on notice and policy errors, the rollout is reversible, and the feature avoids autonomous downstream action. I do not support unrestricted enablement on the calendar date regardless of evidence. Trust is not a disclaimer added after the product works; it is part of the product behavior customers are buying. If we maintain the narrow purpose, visible draft status, transcript grounding, access inheritance, deletion guarantees, and stop conditions, Decision Digest can reduce meeting work without turning participant conversation into an uncontrolled data source. I will own the privacy and security go or no-go decision and remain on the launch review through the first expansion.
        """
    )

    static let launchCustomerSuccessLead = ExampleExcerpt(
        id: "meeting-assistant-launch-customer-success-lead",
        role: "Customer Success Lead",
        audience: "Product Manager, Engineering Lead, Privacy & Security Lead, support, sales, enablement, and account teams",
        meeting: "AI meeting assistant launch readiness",
        text: """
        I am {{name}}, the Customer Success Lead for the Decision Digest launch. I’ll cover what design partners actually experienced, how we will select and enable the first production cohort, what support and account teams need to answer confidently, and which customer signals should pause expansion. I am aligned with the Product Manager’s recommendation for a five-customer conditional launch. My confidence depends less on the calendar date than on whether administrators understand the feature, attendees see the notice, users know the digest is a reviewable draft, and our teams can resolve a question without passing the customer through Product, Engineering, Privacy, and Support separately.

        Across twenty-four design partners, the strongest response came from project teams with recurring planning meetings and distributed membership. Those teams used digests to confirm decisions, catch action items, and help absent colleagues find the relevant transcript moment. Users who opened at least three digests reported saving about fourteen minutes per meeting, and several stopped maintaining a parallel manual decision log. The weakest response came from informal brainstorming sessions, meetings with many external guests, and teams expecting a polished executive summary without review. That pattern supports the proposed scope. We should launch where the product’s structure matches the work rather than encouraging every meeting to generate more content by default.

        Pilot feedback also shows why language matters. Customers trust “draft digest with transcript links” more than “AI meeting minutes.” The first phrase tells them what the feature does and how to verify it. The second sounds official and complete. Administrators asked whether summaries train a shared model, where content is processed, how long derived data remains, who can export it, and what happens when a participant objects. Organizers asked whether external guests are supported and whether action items sync automatically. End users asked how to correct names and whether edits change the transcript. Our enablement package must answer these questions directly, using the same capability matrix reviewed by Product and Privacy.

        I propose five criteria for the first cohort. Each organization must already store meeting transcripts under a documented retention policy, have an administrator willing to complete the Decision Digest checklist, identify an internal owner for participant questions, use one of the supported regions, and nominate teams whose meetings fit the internal scheduled-meeting scope. We should include a mix of North American and European customers, English and at least two supported non-English languages, and both medium and large workspaces. We should exclude customers currently negotiating special retention terms or planning immediate external-meeting use. A launch cohort is an operating partnership, not simply the first five accounts whose sales representatives ask.

        The administrator checklist will explain enablement, organizer choice, attendee notice, supported meeting types, access inheritance, export auditing, retention, deletion requests, and rollback behavior. The administrator must confirm where employees can find their organization’s recording policy and whom they should contact with a concern. We will provide a short organizer guide showing how to enable the feature, review the resulting draft, follow transcript links, correct attribution, and share intentionally. Attendee-facing help will explain why the notice appears and how to raise a question. None of this should require reading a legal memo. The test is whether a new administrator can accurately explain the lifecycle after a twenty-minute setup call.

        Support readiness is organized around observable symptoms rather than internal components. The top cases we expect are a missing digest, delayed processing, an unsupported meeting, incorrect action attribution, a request to delete, a question about notice, an export-access problem, and uncertainty about regional processing. Each playbook begins with customer-safe facts to collect: organization, meeting identifier, approximate completion time, language, visible status, notice result, and error text. Agents should not request the full transcript in a ticket. Cases involving potential unauthorized access, missing notice, regional mismatch, harmful attribution, or overdue deletion enter dedicated escalations with fifteen-minute acknowledgment by the launch team.

        We have trained the specialist support group and will train frontline agents before cohort invitations go out. Training uses eight simulated cases, including contradictory reports from an organizer and participant, a digest delayed by queue pressure, a German meeting with a missed action, and a participant who asks for derived content to be removed. Agents must locate the capability matrix, explain the distinction between digest and source-recording deletion, and route a trust escalation without copying meeting content. Customer Success managers will receive a shorter briefing focused on expectations and stakeholder communication. Sales will receive approved claims and a clear list of capabilities that are not yet available.

        The consent-withdrawal workflow needs one accountable front door. A participant may contact the organization or us, but once the request reaches our team, the receiving agent owns it until the correct workspace administrator and privacy process are engaged. We verify identity using existing account procedures, identify the meeting without asking for unnecessary content, explain that the derived digest will be deleted while source-recording policy is separate, and give a completion expectation. Privacy decides whether additional action is required; Engineering supplies deletion evidence; Customer Success communicates status. The request must not bounce between queues simply because several teams contribute to resolution. Monday’s exercise will test handoffs and customer-facing language, not only backend deletion.

        During the cohort, each organization will have a named Customer Success owner and backup. We will hold a thirty-minute enablement session, a check-in after the first ten digests, and a weekly review during the initial month. A shared launch channel will contain organization identifiers and operational status but no meeting text. The owner will summarize adoption, quality corrections, support cases, administrator questions, and any change in intended use. Product and Engineering can request a customer interview through that owner rather than contacting end users independently. This preserves context and avoids making pilot participants repeat the same concern to four internal teams.

        Customer health metrics will complement the system dashboard. We will track eligible organizations enabled, eligible meetings using the feature, digest open rate, organizer edits, transcript-link use, shares, explicit feedback, and disablement. Support metrics include contacts per hundred enabled workspaces, first-response time, escalation volume, repeated contacts, and unresolved cases. Trust metrics include missing-notice reports, deletion requests, harmful attribution reports, and questions caused by inconsistent documentation. A high edit rate is not automatically failure; editing is part of the intended workflow. We need qualitative sampling to distinguish healthy refinement from a digest so inaccurate that users rewrite it.

        Expansion should pause when customers cannot make safe sense of the experience, even if infrastructure remains green. My stop conditions are one confirmed missing attendee notice, any customer unable to disable generation as documented, a deletion request that misses its commitment, more than one substantiated unsupported decision per thousand digests, more than three support contacts per hundred enabled workspaces, or materially inconsistent answers from account and support teams. A cluster of confusion can justify a hold before it crosses a numerical line. I can trigger that hold, as can Engineering or Privacy, and the launch commander records the decision and customer communication.

        The first-day communication plan is deliberately modest. Cohort administrators receive a direct invitation only after all launch gates are signed. The message states that this is staged general availability, describes supported scope, links the administrator checklist, and names their Customer Success contact. We will not announce unrestricted availability until the cohort review passes. If rollout pauses, administrators receive the known impact, what remains available, any action they should take, and the next update time. We should never call a pause “routine maintenance” if it is actually a quality, notice, or privacy investigation. Precise communication preserves credibility even when the product needs correction.

        I own the administrator checklist, frontline training, cohort selection, escalation roster, and daily voice-of-customer report. Support Operations owns routing rules and case dashboards. Enablement owns the organizer and attendee guides. Each account owner must confirm the customer’s internal contact and intended meeting types before activation. By the go or no-go review, I will provide training completion, simulated-case results, signed cohort checklists, and the published escalation schedule. During the first week, I will join the daily launch review and bring both metrics and verbatim themes, with any customer excerpts minimized and approved for internal use.

        My final recommendation is conditional go because customer value is established and the rollout has a narrow, supportable boundary. The remaining work is not cosmetic: export visibility, withdrawal handling, latency margin, and consistent claims are necessary for customers to trust the feature. If those artifacts pass, we can enroll five organizations and learn responsibly. If any gate fails, I will tell the cohort that we are moving the start date to complete a control, rather than asking them to absorb avoidable risk. Success is not merely that digests generate; it is that administrators and participants understand what happened, can verify the output, retain control, and know exactly where to go when something is wrong.
        """
    )
}
