import Foundation

/// Meeting audio checks: brief turns and longer, multi-paragraph passages.
enum RecallSpeechSamples {
    static let short: [String] = [
        "Can everyone hear me clearly? I am speaking from the local host to check the meeting audio.",
        "Before we begin, let us confirm the agenda and choose the most important decision for today.",
        "The latest build is ready for review. Please share any blockers before we move to the next step.",
        "I agree with the direction. Could we try a small experiment before committing the whole team?",
        "Let me pause there. What questions or concerns should we address before continuing?",
        "Our customer liked the simpler setup, but the instructions still need a clearer example.",
        "We have five minutes left. Let us capture the decision, the owner, and the follow-up date.",
        "The audio sounds steady on my end. I will leave a short pause so another speaker can respond.",
        "Thank you for catching that detail. I will update the notes and send the revised plan after this call.",
        "Good morning, everyone. Today we will compare two options and agree on one practical next step.",
    ]
    static let long: [String] = [
        "I am ready to help test the meeting audio. I will speak at a steady pace so that everyone can check the sound and follow the conversation.\n\nFor our first task, let us agree on one useful outcome for today. We can collect ideas, compare a few options, and choose a clear next step together.\n\nBefore we finish, we will recap the decision and name the person responsible for following up. That way, everyone leaves with the same understanding and a practical plan.",
        "I look forward to hearing everyone's ideas. A thoughtful question can reveal something we have missed, so let us leave room for different perspectives.\n\nImagine we are planning a small community garden. We need to choose a location, decide what to grow, and work out how to share the watering schedule.\n\nA simple plan will help us get started without making everything perfect on the first day. We can learn from the first few weeks and make improvements as we go.",
        "Today is a good day to turn ideas into action. Let us start by describing the problem in plain language and checking that we all mean the same thing.\n\nNext, we can identify one small experiment that would teach us something useful. We should agree on what success looks like and how we will measure the result.\n\nOnce the experiment is complete, we can review the evidence together. Whether the result is encouraging or surprising, it will help us make a better decision about what comes next.",
        "Let us begin our product review with the experience of a first-time customer. They arrive with a goal in mind, and our job is to help them reach it without unnecessary steps.\n\nThis week, we watched several people try the new setup flow. Most completed it successfully, but a few hesitated when choosing their preferences. A clearer example could make that choice easier.\n\nFor the next iteration, we will simplify the wording and test it with a fresh group. We will compare completion times, collect feedback, and bring the results to our next review.",
        "Before we commit to the release date, I would like to review the remaining work. The main features are complete, and the team is now checking reliability, accessibility, and the upgrade experience.\n\nThere are two open questions. First, can we resolve the installation issue by Thursday? Second, do we have enough support coverage for the first day? Each question needs a clear owner and an update.\n\nIf those checks are encouraging, we can proceed with a small rollout. We will watch the results closely and expand only when we are confident the experience is working well.",
        "Thank you for joining this incident review. Our goal is to understand what happened and make the service more reliable. Let us start with the timeline and separate confirmed facts from assumptions.\n\nThe first signal was an increase in response times. The team investigated, identified a slow dependency, and reduced traffic while a fix was prepared. Service recovered after the change was verified.\n\nWe should leave this meeting with a few specific improvements. Better alerts, a clearer response guide, and a realistic load test would each help us respond sooner the next time a similar issue appears.",
        "I would like to use this planning session to make our priorities easier to understand. We have several promising ideas, but our available time is limited, so we need a shared basis for choosing.\n\nFor each proposal, let us describe the customer problem, the expected benefit, and the effort involved. We should also identify any dependencies that could delay progress or change the size of the work.\n\nOnce we have compared the options, we can select a small set of commitments. The remaining ideas will stay in our notes, ready to revisit when we learn more or have additional capacity.",
        "Our team has learned a lot from the pilot program. Participants appreciated the quick start, and several said the weekly check-ins helped them stay focused on their goals. That is a useful signal to build on.\n\nWe also heard requests for more flexible scheduling and better examples. Rather than changing everything at once, we can choose one improvement and see whether it makes a measurable difference.\n\nI suggest we test a shorter onboarding session with an optional follow-up. We will track participation, ask what felt confusing, and review the results together at the end of the month.",
        "Let us walk through the workshop plan before sending the invitation. We want participants to leave with a practical skill they can use immediately, so each section should include time to try something themselves.\n\nWe can begin with a brief demonstration, then move into pairs for a guided exercise. After that, we will invite a few volunteers to share what worked and where they got stuck.\n\nTo finish, everyone can write down one action to take during the following week. We will share the materials afterward and provide a simple way to ask questions as people put the lesson into practice.",
        "I want to close our weekly check-in by recognizing the progress across the team. We finished the research interviews, improved the test environment, and helped a new colleague get comfortable with the project.\n\nNext week, our focus will shift toward validating the design. We need a working prototype, a short list of tasks for participants, and a consistent way to record observations without interrupting the session.\n\nBefore we leave, let us confirm who owns each piece and when it will be ready. If anything becomes blocked, please raise it early so we can adjust the plan and keep the work moving.",
    ]
}
