<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../BotSpeaker/ElevenLabsClient.cs" Link="ElevenLabsClient.cs" />
    <Compile Include="../BotSpeaker/SpeechSynthesisQueue.cs" Link="SpeechSynthesisQueue.cs" />
  </ItemGroup>
</Project>
